CREATE TABLE IF NOT EXISTS packing_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    task_id INT NOT NULL,
    job_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    payload_json LONGTEXT NOT NULL,
    result_json LONGTEXT NULL,
    priority INT NOT NULL DEFAULT 0,
    attempt INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    available_at DATETIME(3) NOT NULL,
    lease_owner VARCHAR(128) NULL,
    lease_token CHAR(36) NULL,
    lease_expires_at DATETIME(3) NULL,
    heartbeat_at DATETIME(3) NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_packing_job_public_id (public_id),
    UNIQUE KEY uk_packing_job_idempotency (idempotency_key),
    KEY idx_packing_job_claim (status, available_at, priority, created_at),
    KEY idx_packing_job_lease (status, lease_expires_at),
    KEY idx_packing_job_task (task_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
